# Generated by Django 4.2.4 on 2024-01-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reg',
        ),
    ]
